### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by smhg** [perchlayer/gettext-volt#1]
Could you add this project to Travis CI?
In short:
- Go to https://travis-ci.org, create/link your account, add gettext-volt.
- Add a .travis.yml config file to the repo (see [smhg/gettext-handlebars](https://github.com/smhg/gettext-handlebars)).
- Nice to have: build status badge (see top of readme in [smhg/gettext-handlebars](https://github.com/smhg/gettext-handlebars)).
- Commit and wait for Travis to complete the test.

**Comment by dschissler** [comment]
Done.  Thanks.
