### ISSUE TITLE
Volt specific test fixtures

### ISSUE THREAD

**Issue by smhg** [perchlayer/gettext-volt#3]
I had a bit more time to look at this and I noticed test/fixtures are exactly the same as [gettext-swig](https://github.com/smhg/gettext-swig)'s.
Looking at the regex differences, there seem to be other Volt formats?
If so, could you add examples of these to the test fixtures? And add tests for these accordingly?
Otherwise, it might be better to rename gettext-swig.

**Comment by dschissler** [comment]
@smhg I got it done.  Please review `gettext-volt` for inclusion into `xgettext-template`.
