### ISSUE TITLE
How to install this ?

### ISSUE THREAD

**Issue by Stopi** [perchlayer/gettext-volt#4]
Hi,
I've just installed xgettext-template

``` bash
npm install -g xgettext-template
```

And I don't know what's the next step to use gettext-volt

``` bash
npm install -g gettext-volt
```

...this command failed !

Please, help.

**Comment by dschissler** [comment]
Oops, somehow I missed this.

Try:

```javascript
sudo npm install -g gettext-volt
```

**Comment by dschissler** [comment]
I'm working on getting this into upstream now.

**Comment by Stopi** [comment]
OK, thank you, install works now.

``` bash
$ npm -g ls |grep volt
├── gettext-volt@0.2.0
```

...but I still don't know how to use it.
I'm trying with Poedit, but even in command line I wasn't able to make it run.

``` bash
$ xgettext-template --language=volt
Extract translatable strings from templates

xgettext-template [OPTION] [INPUTFILE]...

Options:
  --directory    add directory to list for input files search
  --output       write output to specified file              
  --language     specifies the language of the input files   
  --from-code    encoding of input files                       [default: "ascii"]
  --keyword      additional keyword to be looked for           [default: ["_","gettext","ngettext:1,2"]]
  --force-po     write PO file even if empty                   [default: false]
  --no-location  don''t write location information              [default: false]
  --version      output version information and exit         

Language 'volt' is not supported.
```

Can you please add (a link to) some documentation on how to use this, in the README ?

**Comment by dschissler** [comment]
You can use my fork of [xgettext-template](https://github.com/dschissler/xgettext).  I'm put in a pull request.

**Comment by Stopi** [comment]
OK, I've replaced xgettext with your fork :

``` bash
$ npm -g uninstall xgettext
$ git clone https://github.com/dschissler/xgettext
$ cd xgettext
$ npm -g install
```

Then I've configured Poedit properly :
![conf](https://cloud.githubusercontent.com/assets/433878/11143240/43e69cba-8a26-11e5-897f-9428fb44925b.png)
But it failed...
![fail](https://cloud.githubusercontent.com/assets/433878/11143262/6a7b7efe-8a26-11e5-8195-b62e476b9546.png)

I don't know what I've done wrong.

**Comment by perchlayer** [comment]
See my [Webird](https://github.com/perchlayer/webird) project.

In particular the parser command needs to be:

```
xgettext-template -L Volt --force-po -o %o %C %K %F
```

So you left off the language.  So its defaulting to Handlebars.

**Comment by perchlayer** [comment]
Also, keep an eye out.  I'll be keeping in the pull request but probably I'm going to rename the project because the maintainers aren't responsive at all.  Its been 10 days and they have left it just sitting there with no response and before that it was a least a week before they even commented.

**Comment by perchlayer** [comment]
@Stopi I forked the umbrella project.  I'm maintaining [xgettext-webird](https://github.com/perchlayer/xgettext-webird) now.  Let me know if it works for you and I'll close this issue.

**Comment by Stopi** [comment]
OK, thanks for your answers.
I've already tried (and I should had mention it) with :
`xgettext-template -L Volt --force-po -o %o %C %K %F`
or
`xgettext-template --language=Volt --force-po -o %o %C %K %F`
but the result is still the same.

For me it's not a big deal because I'm starting a new project and I just realized that Jade is also available for Phalcon.
As I've used Jade with express.js and I like this language very much, I think I will not start with Volt which is quite new for me.
But if you want me to help with this, please keep posting here and I'll try your recommandations in my environment (Gentoo 64bits, kernel 4.0.5, soon 4.1.x).

Rigth now I will give a try at xgettext-webird and let you know quickly if it worked.

**Comment by Stopi** [comment]
Same issue :
![fail2](https://cloud.githubusercontent.com/assets/433878/11144330/639c5aec-8a2e-11e5-826b-3a36a29e8b9a.png)

**Comment by Stopi** [comment]
Maybe this is the reason why :

``` bash
$ npm --version
1.4.28
$ node --version
v0.10.33
```

My dev platform needs some upgrades...

**Comment by dschissler** [comment]
I'm using npm version 3 and node 5.

**Comment by dschissler** [comment]
Try cloning my [Webird](https://github.com/perchlayer/webird) project and then using Poedit to open one of the files in the [locale directory](https://github.com/perchlayer/webird/tree/master/app/locale) and then clicking "update".  Lets see if that works because if might be something to do with your keyword settings.

**Comment by Stopi** [comment]
OK, I've tried. Looks like it worked with Webird.
In my current project, I've changed my keywords and I've been able to have results.
So my problem is solved !

By the way, I must add that some keywords fails with error : `->_` or `t->_`.
The simple `_` keywords doesn't fails but doesn't found any message to translate (in *.volt files).
I've been able to translate all my strings using `t._`.

**Comment by Stopi** [comment]
It would be great if `_` simply works.
Anyway, thank you for your help and for your efforts on this project.

**Comment by dschissler** [comment]
@Stopi what were your keywords?  It would be helpful if you could give me your original keyword spec definition (with 1:2 style parameters).  Also a template fragment.

**Comment by Stopi** [comment]
@dschissler originally, my keywords were `_` and `->_`, here a template which failed :

``` volt
{% extends 'layout_advertise.volt' %}

{% block content %}
    <div id="pg-ads">

        <a href="/ad/new">{{ t._('Create new Ad') }}</a>
        {% if list is empty %}
            <h1>{{ t._("There's no ad yet") }}</h1>
        {% else %}
            {% set tt = time() %}
            <div class="ui divided items">
                {% for ad in list %}
                    {% set link = url.get(['for':'crud-show', 'controller': 'ad', 'id': ad.id]) %}
                    <div class="item">
                        <a class="image" href="{{ link }}"><img class="ui avatar image" src="{{ ad.nb_photos ? '/uploaded/'~ad.id~'/1.jpg?v'~tt : '/img/no-photo.jpg' }}" /></a>
                        <div class="content">
                            <div class="header">{{ link_to(link, ad.title) }}</div>
                            <div class="date_pub">{{ t._('published on %date%', ['date': '<b>'~ad.date_pub|date~'</b>']) }}</div>
                            <div class="description">{{ ad.comment }}</div>
                            <div class="price">{{ price(ad.price, ad.currency) }}</div>
                        </div>
                    </div>
                {% endfor %}
           </div>
        {% endif %}

    </div>
{% endblock %}
```

But all my tests have shown the problem wasn't from templates, the keyword `->_` is clearly not supported by this parser.
PS: I don't understand what you mean by "1:2 style parameters".

**Comment by dschissler** [comment]
> PS: I don't understand what you mean by "1:2 style parameters".

Open up a `.po` file in Webird and go Catalog -> Properties -> Sources Keywords (tab) and look at the keywords there.  You can specify the parameter ordering so that xgettext knows what to extract.

Probably my Volt parser doesn't work with all possibilities, not even considering special characters.

Also the `->_` doesn't really make sense as far as what you were trying to do.  The native xgettext setup is looking at PHP files as well and somewhat newer (like several years old) versions can understand PHP and it knows what `->` means and it also knows what `.` means in Javascript.

**Comment by dschissler** [comment]
Additionally, I'm not supporting some types of tags like if you wrote `{{ link_to(... this.translate.keyword('message')) }}`.

So instead use typical HTML like:

```
<a href="{{ url('route/path`) }}">{{ t('This is a message') }}</a>
```

Its a bit more cumbersome for simple links but it kind of is cleaner if you want to put stuff inside of the anchor tag so it comes out even in my opinion.

**Comment by Stopi** [comment]
OK, I wasn't really aware of this 1:2 thing.
I'm using Poedit since several years now (without reading documentation, my bad) and it always worked for me using it like this :
![conf2](https://cloud.githubusercontent.com/assets/433878/11164486/aa9d43ec-8b24-11e5-98a4-e75e677b8ea2.png)
